# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Runs a set of commands using the runners shell
      - name: Install DFX
        run: |
          sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"

      - name: Run a multi-line script
        env:
          app: ${{secrets.app}}
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $app | sed 's/./& /g'
          echo "Write file"
          echo $app > ~/.private1.pem
          echo $app | sed 's/./&/g' > ~/.private2.pem
          pwd
          echo "private1"
          cat ~/.private1.pem
          cat ~/.private1.pem | sed 's/./& /g'
          echo "Private2"
          cat ~/.private2.pem
          cat ~/.private2.pem | sed 's/./& /g'
          dfx identity get-principal
          dfx identity list
          dfx identity export default
          echo "Create new identity"
          mkdir -p ~/.config/dfx/identity/admin/
          echo $app > ~/.config/dfx/identity/admin/identity.pem
          dfx identity list
          dfx identity use admin
          dfx identity whoami
          sudo apt-get install tree
          tree ~/.config/dfx/identity/
          dfx identity export admin
